added some bugs
ita-social-projects/Space2Study-node-BackEnd-mvp pull request #126
Opened 2024-02-28 11:23 UTC by Tolik170

2024-03-06 18:32 UTC, vlad-khrychov requested changes

2024-03-06 18:32 UTC, vlad-khrychov commented on src/services/resourcesCategory.js
>      }
Maybe in order to create this bug we can just delete this checking?

2024-03-07 14:09 UTC, Tolik170 commented on src/services/resourcesCategory.js
>      }
You are right, fixed

2024-03-07 14:15 UTC, vlad-khrychov approved these changes

2024-03-07 14:16 UTC, merged