updated readme
ita-social-projects/Space2Study-node-BackEnd-mvp pull request #24
Opened 2024-02-08 09:13 UTC by Tolik170

2024-02-08 11:18 UTC, Marichka0406 approved these changes

2024-02-08 16:39 UTC, Mav-Ivan commented on README.md
> +- Clone this repo to your local machine using `https://github.com/ita-social-projects/Space2Study-node-BackEnd-mvp.git`
Clone this repo to your local machine from BackEnd repository

2024-02-08 16:39 UTC, Mav-Ivan commented on README.md
> +  - 👯 Clone this repo to your local machine using `https://github.com/ita-social-projects/Space2Study-node-BackEnd-mvp.git`
Clone this repo to your local machine using this repository

2024-02-08 16:39 UTC, Mav-Ivan commented on README.md
> +- 🔃 Create a new pull request using <a href="https://github.com/ita-social-projects/Space2Study-node-BackEnd-mvp/compare/" target="_blank">github.com/ita-social-projects/Space2Study-node-BackEnd-mvp<
Create a new pull request in this repository

2024-02-08 16:39 UTC, Mav-Ivan commented on README.md
> +- go to [issues](https://github.com/ita-social-projects/Space2Study-node-BackEnd-mvp/issues) and click `New issue` button
go to Issues and click `New issue` button

2024-02-08 16:39 UTC, Mav-Ivan commented on README.md
> +- when creating [issue](https://github.com/ita-social-projects/Space2Study-node-BackEnd-mvp/issues/new/choose) you should add name of the issue, description, choose assignee, label, project. If issue
when creating issue you should add name of the issue, description, choose assignee, label, project. If issue is a `User Story` you should link it with corresponding tasks, and corresponding tasks should be linked to issue

2024-02-08 16:39 UTC, Mav-Ivan commented on README.md
> +There are three GitHub projects: [SpaceToStudy-Client](https://github.com/ita-social-projects/Space2Study-node-Client-mvp) for frontend part, [SpaceToStudy-BackEnd](https://github.com/ita-social-proj
There are three GitHub projects: SpaceToStudy-Client for frontend part, SpaceToStudy-BackEnd for backend part and admin part is currently under development. Every project has it's own issues

2024-02-08 16:39 UTC, Mav-Ivan commented on README.md
> +You're encouraged to contribute to our project if you've found any issues or missing functionality that you would want to see. Here you can see [the list of issues](https://github.com/ita-social-proj
You're encouraged to contribute to our project if you've found any issues or missing functionality that you would want to see. You can add it to 'Issues' in Issue tab and after that click on 'New issue'

2024-02-13 13:01 UTC, vlad-khrychov requested changes

2024-02-13 13:01 UTC, vlad-khrychov commented on README.md
> +[![GitHub license](https://img.shields.io/github/license/ita-social-projects/Space2Study-node-BackEnd-mvp)](https://github.com/ita-social-projects/Space2Study-node-BackEnd-mvp/tree/LICENSE)
It will be changed after creating repo for group. So we can delete it from readme or leave as empty block smth like
 ```suggestion
[![Pending Pull-Requests](insert your link here)
```
But If we leave these inserts, we need an issue to fill them.

2024-02-22 15:16 UTC, Tolik170 commented on README.md
> +[![GitHub license](https://img.shields.io/github/license/ita-social-projects/Space2Study-node-BackEnd-mvp)](https://github.com/ita-social-projects/Space2Study-node-BackEnd-mvp/tree/LICENSE)
just removed these links

2024-03-06 18:29 UTC, vlad-khrychov approved these changes

2024-03-07 13:27 UTC, merged